### ISSUE TITLE
eid-pt changed to new version and packaging

### ISSUE THREAD

**Issue by ruychi** [caskroom/homebrew-eid#10]
The "Cartão de Cidadão" app is now available at:
url "https://www.cartaodecidadao.pt/ccsoftware/Cartao_de_Cidadao.pkg"

There installation method for the Cask formula needs modifications.
The package installs dylibs in **/usr/local/lib**, as well as some header files in **/usr/local/include/pteid**. It also install two apps in a folder of /Applications:

    /usr/local/lib/libcrypto.1.0.0.dylib
    /usr/local/lib/libjasper.1.0.0.dylib
    /usr/local/lib/libjpeg.9.dylib
    /usr/local/lib/libpteiddlg.1.61.0.dylib
    /usr/local/lib/libpteidhttps.1.61.0.dylib
    /usr/local/lib/libpteidlib.1.61.0.dylib
    /usr/local/lib/libpteidlibopensc.1.61.0.dylib
    /usr/local/lib/libssl.1.0.0.dylib
    /usr/local/lib/pteidpkcs11.1.61.0.dylib

    /usr/local/include/pteid/pteiddefines.h
    /usr/local/include/pteid/pteidlib.h

**Comment by vitorgalvao** [comment]
Updated.
