### ISSUE TITLE
Old version for Belgium EID

### ISSUE THREAD

**Issue by palavrov** [caskroom/homebrew-eid#23]
Just discover that Belgium authority is delivering new EID software than the one in the cask.

It can be downloaded from here: https://eid.belgium.be/fr

I.e. in the tap we have:
4.1.18

The newest one is:
4.2.7

**Comment by vitorgalvao** [comment]
https://github.com/caskroom/homebrew-eid/pull/24

**Comment by palavrov** [comment]
Arrrgh ... it was so quick - you need to upgrade also
be-eid-viewer - from the same link
be-eid-midleware - for that one don't know
